# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  database: my_rails_app_development

test:
  <<: *default
  database: my_rails_app_test

production:
    url: <%= ENV["DATABASE_URL"] %>
